set(_CATKIN_CURRENT_PACKAGE "rostxtest_mod")
set(rostxtest_mod_VERSION "1.0.0")
set(rostxtest_mod_MAINTAINER "Lenny Lee <qq1021620522@gmail.com>")
set(rostxtest_mod_PACKAGE_FORMAT "3")
set(rostxtest_mod_BUILD_DEPENDS "roscpp" "std_msgs")
set(rostxtest_mod_BUILD_EXPORT_DEPENDS )
set(rostxtest_mod_BUILDTOOL_DEPENDS "catkin")
set(rostxtest_mod_BUILDTOOL_EXPORT_DEPENDS )
set(rostxtest_mod_EXEC_DEPENDS "roscpp" "std_msgs")
set(rostxtest_mod_RUN_DEPENDS "roscpp" "std_msgs")
set(rostxtest_mod_TEST_DEPENDS )
set(rostxtest_mod_DOC_DEPENDS )
set(rostxtest_mod_URL_WEBSITE "")
set(rostxtest_mod_URL_BUGTRACKER "")
set(rostxtest_mod_URL_REPOSITORY "")
set(rostxtest_mod_DEPRECATED "")