set(_CATKIN_CURRENT_PACKAGE "pro_lower_controller")
set(pro_lower_controller_VERSION "0.0.0")
set(pro_lower_controller_MAINTAINER "roma <qq1021620522@gmail.com>")
set(pro_lower_controller_PACKAGE_FORMAT "2")
set(pro_lower_controller_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(pro_lower_controller_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(pro_lower_controller_BUILDTOOL_DEPENDS "catkin")
set(pro_lower_controller_BUILDTOOL_EXPORT_DEPENDS )
set(pro_lower_controller_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(pro_lower_controller_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(pro_lower_controller_TEST_DEPENDS )
set(pro_lower_controller_DOC_DEPENDS )
set(pro_lower_controller_URL_WEBSITE "")
set(pro_lower_controller_URL_BUGTRACKER "")
set(pro_lower_controller_URL_REPOSITORY "")
set(pro_lower_controller_DEPRECATED "")