set(_CATKIN_CURRENT_PACKAGE "sbus_serial")
set(sbus_serial_VERSION "1.0.0")
set(sbus_serial_MAINTAINER "Jens Willy Johannsen <jens@jwrobotics.com>")
set(sbus_serial_PACKAGE_FORMAT "2")
set(sbus_serial_BUILD_DEPENDS "roscpp" "geometry_msgs" "std_msgs" "message_generation")
set(sbus_serial_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "std_msgs")
set(sbus_serial_BUILDTOOL_DEPENDS "catkin")
set(sbus_serial_BUILDTOOL_EXPORT_DEPENDS )
set(sbus_serial_EXEC_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "message_runtime")
set(sbus_serial_RUN_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "message_runtime")
set(sbus_serial_TEST_DEPENDS )
set(sbus_serial_DOC_DEPENDS )
set(sbus_serial_URL_WEBSITE "")
set(sbus_serial_URL_BUGTRACKER "")
set(sbus_serial_URL_REPOSITORY "")
set(sbus_serial_DEPRECATED "")